import test from 'node:test';
import assert from 'node:assert/strict';
import { STAMINA_RECOVERY_MS, createFullStamina, decodeStamina, grantAdStamina, nextRecoveryMs, reconcileStamina, spendStamina } from '../assets/scripts/core/stamina.ts';
test('new and invalid stamina start full without touching other progress', () => { assert.deepEqual(createFullStamina(1_000), { schemaVersion: 1, value: 10, updatedAt: 1_000 }); assert.deepEqual(decodeStamina('{bad', 2_000), createFullStamina(2_000)); assert.deepEqual(decodeStamina(JSON.stringify({ schemaVersion: 1, value: 11, updatedAt: 0 }), 2_000), createFullStamina(2_000)); });
test('recovery keeps partial time and caps at ten', () => { const state = { schemaVersion: 1, value: 7, updatedAt: 1_000 } as const; const now = 1_000 + STAMINA_RECOVERY_MS * 2 + 12_345; assert.deepEqual(reconcileStamina(state, now), { schemaVersion: 1, value: 9, updatedAt: 1_000 + STAMINA_RECOVERY_MS * 2 }); assert.equal(nextRecoveryMs(state, now), STAMINA_RECOVERY_MS - 12_345); assert.equal(reconcileStamina(state, 0), state); });
test('spending and ad rewards obey zero and maximum boundaries', () => { assert.equal(spendStamina({ schemaVersion: 1, value: 0, updatedAt: 1_000 }, 2_000), null); assert.deepEqual(spendStamina(createFullStamina(1_000), 2_000), { schemaVersion: 1, value: 9, updatedAt: 2_000 }); assert.deepEqual(grantAdStamina({ schemaVersion: 1, value: 4, updatedAt: 1_000 }, 2_000), { schemaVersion: 1, value: 9, updatedAt: 1_000 }); assert.deepEqual(grantAdStamina({ schemaVersion: 1, value: 8, updatedAt: 1_000 }, 2_000), createFullStamina(2_000)); });
test('time reversal never moves the spending recovery baseline backward', () => { const state = { schemaVersion: 1, value: 5, updatedAt: 2_000_000 } as const; assert.deepEqual(spendStamina(state, 1_000_000), { schemaVersion: 1, value: 4, updatedAt: 2_000_000 }); });
test('time reversal reports one complete recovery period', () => { const state = { schemaVersion: 1, value: 5, updatedAt: 2_000_000 } as const; assert.equal(nextRecoveryMs(state, 1_000_000), STAMINA_RECOVERY_MS); });
test('ad reward reconciles offline recovery before adding the reward', () => { const state = { schemaVersion: 1, value: 3, updatedAt: 1_000 } as const; assert.deepEqual(grantAdStamina(state, 1_000 + STAMINA_RECOVERY_MS * 2), { schemaVersion: 1, value: 10, updatedAt: 1_000 + STAMINA_RECOVERY_MS * 2 }); });
