import type { LevelConfig } from './level-config.ts';

// Generated by tools/generate-chapter-nine.ts. Do not edit by hand.
export const CHAPTER_NINE_LEVEL_DATA: readonly LevelConfig[] = [
  {
    "id": "level-241",
    "number": 241,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 241,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 37,
      "segmentCount": 43,
      "exploredStates": 54389,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.803,
      "difficultyScore": 8030
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "rose",
            "lilac",
            "amber",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "blue",
            "chartreuse",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "cyan",
            "gold",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "mint",
            "mint",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "violet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "amber",
            "chartreuse",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "indigo",
            "cyan",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "scarlet",
            "lilac",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "cyan",
            "rose",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "scarlet",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "rose",
            "cyan",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-242",
    "number": 242,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 242,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 58138,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.18181818181818182,
      "difficultyRating": 0.778,
      "difficultyScore": 7780
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "rose",
            "scarlet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "mint",
            "scarlet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "mint",
            "violet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "indigo",
            "mint",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "violet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "rose",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "amber",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "indigo",
            "amber",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "violet",
            "cyan",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-243",
    "number": 243,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 243,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 73047,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.6363636363636364,
      "difficultyRating": 0.845,
      "difficultyScore": 8450
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "gold",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "chartreuse",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "violet",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "mint",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "blue",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "scarlet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "rose",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "chartreuse",
            "mint",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-244",
    "number": 244,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 244,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 38,
      "segmentCount": 44,
      "exploredStates": 87150,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.809,
      "difficultyScore": 8090
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "indigo",
            "violet",
            "lilac",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "lilac",
            "chartreuse",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "violet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "rose",
            "amber",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "amber",
            "mint",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "amber",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "scarlet",
            "gold",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "gold",
            "violet",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "gold",
            "blue",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "chartreuse",
            "rose",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-245",
    "number": 245,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 245,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 63487,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.805,
      "difficultyScore": 8050
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "cyan",
            "rose",
            "scarlet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "violet",
            "scarlet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "mint",
            "violet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "indigo",
            "mint",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "violet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "rose",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "amber",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "indigo",
            "amber",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "mint",
            "chartreuse",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-246",
    "number": 246,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 246,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 38,
      "segmentCount": 44,
      "exploredStates": 79145,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.6363636363636364,
      "difficultyRating": 0.846,
      "difficultyScore": 8460
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "gold",
            "rose",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "chartreuse",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "violet",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "blue",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "scarlet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "chartreuse",
            "mint",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-247",
    "number": 247,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 247,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 38,
      "segmentCount": 44,
      "exploredStates": 92124,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.81,
      "difficultyScore": 8100
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "indigo",
            "violet",
            "lilac",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "lilac",
            "chartreuse",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "lilac",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "rose",
            "amber",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "amber",
            "mint",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "amber",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "scarlet",
            "gold",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "gold",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "gold",
            "blue",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "chartreuse",
            "rose",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-248",
    "number": 248,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 248,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 62040,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.805,
      "difficultyScore": 8050
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "cyan",
            "rose",
            "scarlet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "mint",
            "scarlet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "mint",
            "violet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "indigo",
            "mint",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "violet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "rose",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "amber",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "indigo",
            "amber",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "scarlet",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "violet",
            "chartreuse",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-249",
    "number": 249,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 249,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 38,
      "segmentCount": 44,
      "exploredStates": 64502,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.6363636363636364,
      "difficultyRating": 0.843,
      "difficultyScore": 8430
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "gold",
            "mint",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "chartreuse",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "violet",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "rose",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "blue",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "scarlet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "rose",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "chartreuse",
            "mint",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-250",
    "number": 250,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 250,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 38,
      "segmentCount": 44,
      "exploredStates": 92814,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.81,
      "difficultyScore": 8100
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "indigo",
            "violet",
            "lilac",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "lilac",
            "chartreuse",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "violet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "rose",
            "amber",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "scarlet",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "mint",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "amber",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "scarlet",
            "gold",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "gold",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "gold",
            "blue",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "chartreuse",
            "rose",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-251",
    "number": 251,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 251,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 40,
      "segmentCount": 44,
      "exploredStates": 74422,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.18181818181818182,
      "difficultyRating": 0.782,
      "difficultyScore": 7820
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "cyan",
            "rose",
            "scarlet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "mint",
            "scarlet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "mint",
            "violet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "indigo",
            "lilac",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "violet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "rose",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "amber",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "indigo",
            "amber",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "chartreuse",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "violet",
            "chartreuse",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-252",
    "number": 252,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 252,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 74501,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.6363636363636364,
      "difficultyRating": 0.845,
      "difficultyScore": 8450
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "gold",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "mint",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "violet",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "rose",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "blue",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "scarlet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "rose",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "chartreuse",
            "mint",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-253",
    "number": 253,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 253,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 38,
      "segmentCount": 44,
      "exploredStates": 93303,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.45454545454545453,
      "difficultyRating": 0.823,
      "difficultyScore": 8230
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "indigo",
            "violet",
            "lilac",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "lilac",
            "chartreuse",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "violet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "rose",
            "amber",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "amber",
            "cyan",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "amber",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "scarlet",
            "gold",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "gold",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "gold",
            "blue",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "chartreuse",
            "rose",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-254",
    "number": 254,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 254,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 40,
      "segmentCount": 44,
      "exploredStates": 62731,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.18181818181818182,
      "difficultyRating": 0.779,
      "difficultyScore": 7790
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "cyan",
            "rose",
            "scarlet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "mint",
            "scarlet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "mint",
            "violet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "indigo",
            "amber",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "violet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "rose",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "amber",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "indigo",
            "mint",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "violet",
            "chartreuse",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-255",
    "number": 255,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 255,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 77702,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.2727272727272727,
      "difficultyRating": 0.795,
      "difficultyScore": 7950
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "gold",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "chartreuse",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "violet",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "amber",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "blue",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "scarlet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "rose",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "chartreuse",
            "mint",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-256",
    "number": 256,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 256,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 38,
      "segmentCount": 44,
      "exploredStates": 93434,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.45454545454545453,
      "difficultyRating": 0.823,
      "difficultyScore": 8230
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "indigo",
            "violet",
            "lilac",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "lilac",
            "chartreuse",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "violet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "rose",
            "amber",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "amber",
            "mint",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "cyan",
            "amber",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "scarlet",
            "gold",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "gold",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "gold",
            "blue",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "chartreuse",
            "rose",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-257",
    "number": 257,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 257,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 64047,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.805,
      "difficultyScore": 8050
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "cyan",
            "rose",
            "violet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "mint",
            "scarlet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "mint",
            "violet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "indigo",
            "mint",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "scarlet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "rose",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "amber",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "indigo",
            "amber",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "violet",
            "chartreuse",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-258",
    "number": 258,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 258,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 66427,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.45454545454545453,
      "difficultyRating": 0.818,
      "difficultyScore": 8180
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "amber",
            "gold",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "chartreuse",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "violet",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "blue",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "lilac",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "scarlet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "rose",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "chartreuse",
            "mint",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-259",
    "number": 259,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 259,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 38,
      "segmentCount": 44,
      "exploredStates": 95059,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.81,
      "difficultyScore": 8100
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "indigo",
            "violet",
            "lilac",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "scarlet",
            "chartreuse",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "violet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "rose",
            "amber",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "lilac",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "amber",
            "mint",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "amber",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "scarlet",
            "gold",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "gold",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "gold",
            "blue",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "chartreuse",
            "rose",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-260",
    "number": 260,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 260,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 66701,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.806,
      "difficultyScore": 8060
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "cyan",
            "mint",
            "scarlet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "rose",
            "scarlet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "mint",
            "violet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "indigo",
            "mint",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "violet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "rose",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "amber",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "indigo",
            "amber",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "violet",
            "chartreuse",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-261",
    "number": 261,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 261,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 70608,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.6363636363636364,
      "difficultyRating": 0.845,
      "difficultyScore": 8450
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "rose",
            "gold",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "chartreuse",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "violet",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "blue",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "scarlet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "chartreuse",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "chartreuse",
            "mint",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-262",
    "number": 262,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 262,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 38,
      "segmentCount": 44,
      "exploredStates": 103371,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.811,
      "difficultyScore": 8110
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "indigo",
            "violet",
            "lilac",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "scarlet",
            "chartreuse",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "violet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "rose",
            "amber",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "amber",
            "mint",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "amber",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "lilac",
            "gold",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "gold",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "gold",
            "blue",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "chartreuse",
            "rose",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-263",
    "number": 263,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 263,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 71571,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.18181818181818182,
      "difficultyRating": 0.781,
      "difficultyScore": 7810
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "cyan",
            "rose",
            "scarlet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "mint",
            "scarlet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "mint",
            "violet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "violet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "indigo",
            "mint",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "violet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "rose",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "amber",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "indigo",
            "amber",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "violet",
            "blue",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-264",
    "number": 264,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 264,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 88901,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.18181818181818182,
      "difficultyRating": 0.784,
      "difficultyScore": 7840
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "gold",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "chartreuse",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "violet",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "blue",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "scarlet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "rose",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "chartreuse",
            "mint",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-265",
    "number": 265,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 265,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 40,
      "segmentCount": 44,
      "exploredStates": 70146,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.09090909090909091,
      "difficultyRating": 0.768,
      "difficultyScore": 7680
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "cyan",
            "rose",
            "scarlet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "mint",
            "scarlet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "mint",
            "violet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "indigo",
            "mint",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "violet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "rose",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "chartreuse",
            "amber",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "indigo",
            "amber",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "violet",
            "chartreuse",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-266",
    "number": 266,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 266,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 78994,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.808,
      "difficultyScore": 8080
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "gold",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "chartreuse",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "violet",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "chartreuse",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "blue",
            "lilac",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "scarlet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "rose",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "chartreuse",
            "mint",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-267",
    "number": 267,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 267,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 114443,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.18181818181818182,
      "difficultyRating": 0.787,
      "difficultyScore": 7870
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "indigo",
            "violet",
            "lilac",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "lilac",
            "chartreuse",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "violet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "rose",
            "amber",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "blue",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "amber",
            "mint",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "amber",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "scarlet",
            "gold",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "gold",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "gold",
            "mint",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "chartreuse",
            "rose",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-268",
    "number": 268,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 268,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 38,
      "segmentCount": 44,
      "exploredStates": 67199,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.806,
      "difficultyScore": 8060
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "rose",
            "mint",
            "gold",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "gold",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "lilac",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "amber",
            "lilac",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "violet",
            "cyan",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "indigo",
            "cyan",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "mint",
            "lilac",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "gold",
            "mint",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "indigo",
            "rose",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "scarlet",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "lilac",
            "violet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-269",
    "number": 269,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 269,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 38,
      "segmentCount": 44,
      "exploredStates": 77714,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.808,
      "difficultyScore": 8080
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "rose",
            "gold",
            "cyan",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "gold",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "lilac",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "amber",
            "lilac",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "violet",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "indigo",
            "cyan",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "mint",
            "lilac",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "gold",
            "mint",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "indigo",
            "rose",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "scarlet",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "lilac",
            "violet",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-270",
    "number": 270,
    "configVersion": "chapter-9.2026-09-23.1",
    "presentationSeed": 270,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 38,
      "segmentCount": 44,
      "exploredStates": 79377,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.808,
      "difficultyScore": 8080
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "rose",
            "mint",
            "gold",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "gold",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "lilac",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "amber",
            "lilac",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "violet",
            "cyan",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "indigo",
            "cyan",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "gold",
            "lilac",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "gold",
            "mint",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "indigo",
            "rose",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "scarlet",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "lilac",
            "violet",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  }
];
