import type { LevelConfig } from './level-config.ts';

// Generated by tools/generate-chapter-three.ts. Do not edit by hand.
export const CHAPTER_FOUR_LEVEL_DATA: readonly LevelConfig[] = [
  {
    "id": "level-091",
    "number": 91,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 91,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 9
    },
    "metrics": {
      "colorCount": 9,
      "optimalMoves": 25,
      "segmentCount": 32,
      "exploredStates": 11466,
      "openingMoves": 18,
      "misleadingBranchRatio": 0.4444444444444444,
      "difficultyRating": 0.694,
      "difficultyScore": 6940
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "violet",
            "rose",
            "cyan",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "amber",
            "lilac",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "violet",
            "violet",
            "rose",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "cyan",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "mint",
            "blue",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "lilac",
            "lilac",
            "cyan",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "scarlet",
            "blue",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "mint",
            "amber",
            "gold",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "amber",
            "scarlet",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-092",
    "number": 92,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 92,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 9
    },
    "metrics": {
      "colorCount": 9,
      "optimalMoves": 26,
      "segmentCount": 32,
      "exploredStates": 15162,
      "openingMoves": 18,
      "misleadingBranchRatio": 0.4444444444444444,
      "difficultyRating": 0.71,
      "difficultyScore": 7100
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "rose",
            "lilac",
            "mint",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "amber",
            "cyan",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "gold",
            "mint",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "scarlet",
            "scarlet",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "blue",
            "blue",
            "lilac",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "blue",
            "cyan",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "lilac",
            "violet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "gold",
            "amber",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "rose",
            "amber",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-093",
    "number": 93,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 93,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 9
    },
    "metrics": {
      "colorCount": 9,
      "optimalMoves": 26,
      "segmentCount": 33,
      "exploredStates": 10309,
      "openingMoves": 18,
      "misleadingBranchRatio": 0.5555555555555556,
      "difficultyRating": 0.72,
      "difficultyScore": 7200
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "cyan",
            "blue",
            "lilac",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "lilac",
            "blue",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "cyan",
            "mint",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "amber",
            "mint",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "violet",
            "scarlet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "violet",
            "gold",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "blue",
            "blue",
            "rose",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "cyan",
            "rose",
            "violet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "mint",
            "amber",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-094",
    "number": 94,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 94,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 9
    },
    "metrics": {
      "colorCount": 9,
      "optimalMoves": 25,
      "segmentCount": 32,
      "exploredStates": 5723,
      "openingMoves": 18,
      "misleadingBranchRatio": 0.6666666666666666,
      "difficultyRating": 0.716,
      "difficultyScore": 7160
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "violet",
            "violet",
            "blue",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "amber",
            "mint",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "mint",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "lilac",
            "mint",
            "scarlet",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "gold",
            "blue",
            "lilac",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "lilac",
            "lilac",
            "cyan",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "gold",
            "blue",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "rose",
            "rose",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "violet",
            "gold",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-095",
    "number": 95,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 95,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 9
    },
    "metrics": {
      "colorCount": 9,
      "optimalMoves": 25,
      "segmentCount": 32,
      "exploredStates": 11466,
      "openingMoves": 18,
      "misleadingBranchRatio": 0.4444444444444444,
      "difficultyRating": 0.694,
      "difficultyScore": 6940
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "amber",
            "mint",
            "cyan",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "rose",
            "gold",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "amber",
            "mint",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "scarlet",
            "scarlet",
            "lilac",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "blue",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "cyan",
            "gold",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "scarlet",
            "rose",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "violet",
            "amber",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "lilac",
            "lilac",
            "mint",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-096",
    "number": 96,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 96,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 9
    },
    "metrics": {
      "colorCount": 9,
      "optimalMoves": 26,
      "segmentCount": 32,
      "exploredStates": 15162,
      "openingMoves": 18,
      "misleadingBranchRatio": 0.4444444444444444,
      "difficultyRating": 0.71,
      "difficultyScore": 7100
    },
    "initialState": {
      "bottles": [
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "rose",
            "rose",
            "rose",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "scarlet",
            "lilac",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "blue",
            "amber",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "cyan",
            "lilac",
            "mint",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "rose",
            "violet",
            "mint",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "blue",
            "cyan",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "violet",
            "blue",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "scarlet",
            "amber",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "lilac",
            "gold",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-097",
    "number": 97,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 97,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 9
    },
    "metrics": {
      "colorCount": 9,
      "optimalMoves": 26,
      "segmentCount": 33,
      "exploredStates": 10309,
      "openingMoves": 18,
      "misleadingBranchRatio": 0.5555555555555556,
      "difficultyRating": 0.72,
      "difficultyScore": 7200
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "gold",
            "gold",
            "lilac",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "scarlet",
            "blue",
            "violet",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "cyan",
            "amber",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "violet",
            "blue",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "scarlet",
            "gold",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "amber",
            "mint",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "blue",
            "cyan",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "lilac",
            "gold",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "lilac",
            "amber",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-098",
    "number": 98,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 98,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 9
    },
    "metrics": {
      "colorCount": 9,
      "optimalMoves": 26,
      "segmentCount": 32,
      "exploredStates": 15162,
      "openingMoves": 18,
      "misleadingBranchRatio": 0.4444444444444444,
      "difficultyRating": 0.71,
      "difficultyScore": 7100
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "rose",
            "scarlet",
            "mint",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "gold",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "amber",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "blue",
            "blue",
            "blue",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "amber",
            "mint",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "lilac",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "lilac",
            "scarlet",
            "cyan",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "lilac",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "violet",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-099",
    "number": 99,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 99,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 9
    },
    "metrics": {
      "colorCount": 9,
      "optimalMoves": 26,
      "segmentCount": 32,
      "exploredStates": 15162,
      "openingMoves": 18,
      "misleadingBranchRatio": 0.4444444444444444,
      "difficultyRating": 0.71,
      "difficultyScore": 7100
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "rose",
            "amber",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "scarlet",
            "blue",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "amber",
            "lilac",
            "amber",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "cyan",
            "cyan",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "lilac",
            "blue",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "mint",
            "scarlet",
            "rose",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "mint",
            "scarlet",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "amber",
            "gold",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-100",
    "number": 100,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 100,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 9
    },
    "metrics": {
      "colorCount": 9,
      "optimalMoves": 26,
      "segmentCount": 32,
      "exploredStates": 15162,
      "openingMoves": 18,
      "misleadingBranchRatio": 0.4444444444444444,
      "difficultyRating": 0.71,
      "difficultyScore": 7100
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "blue",
            "blue",
            "mint",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "blue",
            "mint",
            "amber",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "rose",
            "lilac",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "scarlet",
            "violet",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "violet",
            "mint",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "gold",
            "blue",
            "cyan",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "rose",
            "scarlet",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "gold",
            "gold",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "scarlet",
            "cyan",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-101",
    "number": 101,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 101,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 9
    },
    "metrics": {
      "colorCount": 9,
      "optimalMoves": 26,
      "segmentCount": 33,
      "exploredStates": 10309,
      "openingMoves": 18,
      "misleadingBranchRatio": 0.5555555555555556,
      "difficultyRating": 0.72,
      "difficultyScore": 7200
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "rose",
            "violet",
            "scarlet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "gold",
            "mint",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "blue",
            "amber",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "gold",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "violet",
            "rose",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "amber",
            "amber",
            "blue",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "cyan",
            "amber",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "lilac",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "mint",
            "lilac",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-102",
    "number": 102,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 102,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 10
    },
    "metrics": {
      "colorCount": 10,
      "optimalMoves": 27,
      "segmentCount": 35,
      "exploredStates": 5899,
      "openingMoves": 20,
      "misleadingBranchRatio": 0.8,
      "difficultyRating": 0.749,
      "difficultyScore": 7490
    },
    "initialState": {
      "bottles": [
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "gold",
            "rose",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "chartreuse",
            "lilac",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "cyan",
            "scarlet",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "lilac",
            "scarlet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "mint",
            "blue",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "gold",
            "amber",
            "rose",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "rose",
            "mint",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "scarlet",
            "lilac",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "violet",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "amber",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-103",
    "number": 103,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 103,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 10
    },
    "metrics": {
      "colorCount": 10,
      "optimalMoves": 27,
      "segmentCount": 35,
      "exploredStates": 14443,
      "openingMoves": 20,
      "misleadingBranchRatio": 0.6,
      "difficultyRating": 0.733,
      "difficultyScore": 7330
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "lilac",
            "rose",
            "amber",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "lilac",
            "scarlet",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "chartreuse",
            "scarlet",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "blue",
            "blue",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "mint",
            "cyan",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "rose",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "lilac",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "rose",
            "blue",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "violet",
            "gold",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "cyan",
            "gold",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-104",
    "number": 104,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 104,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 10
    },
    "metrics": {
      "colorCount": 10,
      "optimalMoves": 28,
      "segmentCount": 35,
      "exploredStates": 15962,
      "openingMoves": 20,
      "misleadingBranchRatio": 0.4,
      "difficultyRating": 0.718,
      "difficultyScore": 7180
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "chartreuse",
            "violet",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "scarlet",
            "scarlet",
            "lilac",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "lilac",
            "cyan",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "gold",
            "blue",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "blue",
            "amber",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "rose",
            "mint",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "cyan",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "mint",
            "gold",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "scarlet",
            "mint",
            "rose",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-105",
    "number": 105,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 105,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 10
    },
    "metrics": {
      "colorCount": 10,
      "optimalMoves": 27,
      "segmentCount": 35,
      "exploredStates": 13685,
      "openingMoves": 20,
      "misleadingBranchRatio": 0.5,
      "difficultyRating": 0.718,
      "difficultyScore": 7180
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "lilac",
            "lilac",
            "amber",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "scarlet",
            "blue",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "chartreuse",
            "scarlet",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "amber",
            "scarlet",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "rose",
            "violet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "rose",
            "rose",
            "lilac",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "rose",
            "cyan",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "gold",
            "amber",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "violet",
            "blue",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "mint",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-106",
    "number": 106,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 106,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 10
    },
    "metrics": {
      "colorCount": 10,
      "optimalMoves": 27,
      "segmentCount": 35,
      "exploredStates": 14650,
      "openingMoves": 20,
      "misleadingBranchRatio": 0.6,
      "difficultyRating": 0.733,
      "difficultyScore": 7330
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "chartreuse",
            "cyan",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "amber",
            "rose",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "scarlet",
            "gold",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "mint",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "lilac",
            "blue",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "amber",
            "cyan",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "amber",
            "scarlet",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "violet",
            "lilac",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "rose",
            "rose",
            "blue",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "mint",
            "gold",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-107",
    "number": 107,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 107,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 10
    },
    "metrics": {
      "colorCount": 10,
      "optimalMoves": 28,
      "segmentCount": 35,
      "exploredStates": 16408,
      "openingMoves": 20,
      "misleadingBranchRatio": 0.5,
      "difficultyRating": 0.732,
      "difficultyScore": 7320
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "chartreuse",
            "cyan",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "blue",
            "rose",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "blue",
            "scarlet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "violet",
            "violet",
            "violet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "lilac",
            "amber",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "lilac",
            "mint",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "rose",
            "gold",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "cyan",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "rose",
            "amber",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "mint",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-108",
    "number": 108,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 108,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 10
    },
    "metrics": {
      "colorCount": 10,
      "optimalMoves": 28,
      "segmentCount": 36,
      "exploredStates": 7888,
      "openingMoves": 20,
      "misleadingBranchRatio": 0.6,
      "difficultyRating": 0.737,
      "difficultyScore": 7370
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "chartreuse",
            "blue",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "gold",
            "scarlet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "blue",
            "scarlet",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "scarlet",
            "blue",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "violet",
            "amber",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "blue",
            "cyan",
            "lilac",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "violet",
            "rose",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "amber",
            "cyan",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "cyan",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "amber",
            "rose",
            "violet",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-109",
    "number": 109,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 109,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 10
    },
    "metrics": {
      "colorCount": 10,
      "optimalMoves": 27,
      "segmentCount": 35,
      "exploredStates": 12732,
      "openingMoves": 20,
      "misleadingBranchRatio": 0.5,
      "difficultyRating": 0.717,
      "difficultyScore": 7170
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "lilac",
            "cyan",
            "blue",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "mint",
            "violet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "cyan",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "violet",
            "gold",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "rose",
            "amber",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "scarlet",
            "gold",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "chartreuse",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "gold",
            "lilac",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "gold",
            "cyan",
            "rose",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "lilac",
            "amber",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-110",
    "number": 110,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 110,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 10
    },
    "metrics": {
      "colorCount": 10,
      "optimalMoves": 27,
      "segmentCount": 35,
      "exploredStates": 12441,
      "openingMoves": 20,
      "misleadingBranchRatio": 0.5,
      "difficultyRating": 0.717,
      "difficultyScore": 7170
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "blue",
            "violet",
            "amber",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "mint",
            "gold",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "amber",
            "rose",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "chartreuse",
            "rose",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "cyan",
            "amber",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "blue",
            "rose",
            "lilac",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "mint",
            "cyan",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "mint",
            "scarlet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "scarlet",
            "lilac",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "blue",
            "blue",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-111",
    "number": 111,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 111,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 10
    },
    "metrics": {
      "colorCount": 10,
      "optimalMoves": 28,
      "segmentCount": 35,
      "exploredStates": 15859,
      "openingMoves": 20,
      "misleadingBranchRatio": 0.6,
      "difficultyRating": 0.746,
      "difficultyScore": 7460
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "violet",
            "cyan",
            "rose",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "amber",
            "lilac",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "mint",
            "amber",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "violet",
            "cyan",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "chartreuse",
            "blue",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "mint",
            "mint",
            "blue",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "scarlet",
            "scarlet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "cyan",
            "blue",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "amber",
            "gold",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "violet",
            "lilac",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-112",
    "number": 112,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 112,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 10
    },
    "metrics": {
      "colorCount": 10,
      "optimalMoves": 28,
      "segmentCount": 36,
      "exploredStates": 12820,
      "openingMoves": 20,
      "misleadingBranchRatio": 0.6,
      "difficultyRating": 0.743,
      "difficultyScore": 7430
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "amber",
            "gold",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "chartreuse",
            "mint",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "gold",
            "amber",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "gold",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "cyan",
            "rose",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "blue",
            "mint",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "violet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "violet",
            "blue",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "lilac",
            "rose",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "rose",
            "rose",
            "lilac",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-113",
    "number": 113,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 113,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 10
    },
    "metrics": {
      "colorCount": 10,
      "optimalMoves": 27,
      "segmentCount": 35,
      "exploredStates": 14440,
      "openingMoves": 20,
      "misleadingBranchRatio": 0.6,
      "difficultyRating": 0.733,
      "difficultyScore": 7330
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "chartreuse",
            "amber",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "violet",
            "mint",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "cyan",
            "cyan",
            "scarlet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "rose",
            "blue",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "lilac",
            "rose",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "mint",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "lilac",
            "cyan",
            "gold",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "gold",
            "blue",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "scarlet",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "cyan",
            "amber",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-114",
    "number": 114,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 114,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 10
    },
    "metrics": {
      "colorCount": 10,
      "optimalMoves": 27,
      "segmentCount": 35,
      "exploredStates": 12750,
      "openingMoves": 20,
      "misleadingBranchRatio": 0.5,
      "difficultyRating": 0.717,
      "difficultyScore": 7170
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "gold",
            "amber",
            "violet",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "blue",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "chartreuse",
            "rose",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "cyan",
            "mint",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "cyan",
            "rose",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "amber",
            "violet",
            "blue",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "cyan",
            "lilac",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "mint",
            "mint",
            "scarlet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "gold",
            "amber",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "rose",
            "violet",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-115",
    "number": 115,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 115,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 10
    },
    "metrics": {
      "colorCount": 10,
      "optimalMoves": 27,
      "segmentCount": 35,
      "exploredStates": 8534,
      "openingMoves": 20,
      "misleadingBranchRatio": 0.7,
      "difficultyRating": 0.74,
      "difficultyScore": 7400
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "chartreuse",
            "scarlet",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "cyan",
            "violet",
            "rose",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "gold",
            "cyan",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "blue",
            "amber",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "scarlet",
            "rose",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "blue",
            "mint",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "mint",
            "gold",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "amber",
            "mint",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "lilac",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "gold",
            "rose",
            "violet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-116",
    "number": 116,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 116,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 10
    },
    "metrics": {
      "colorCount": 10,
      "optimalMoves": 27,
      "segmentCount": 35,
      "exploredStates": 9398,
      "openingMoves": 20,
      "misleadingBranchRatio": 0.5,
      "difficultyRating": 0.713,
      "difficultyScore": 7130
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "violet",
            "violet",
            "rose",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "chartreuse",
            "rose",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "lilac",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "scarlet",
            "gold",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "amber",
            "blue",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "scarlet",
            "cyan",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "blue",
            "mint",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "rose",
            "amber",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "gold",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "cyan",
            "amber",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-117",
    "number": 117,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 117,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 10
    },
    "metrics": {
      "colorCount": 10,
      "optimalMoves": 28,
      "segmentCount": 35,
      "exploredStates": 15085,
      "openingMoves": 20,
      "misleadingBranchRatio": 0.6,
      "difficultyRating": 0.745,
      "difficultyScore": 7450
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "violet",
            "violet",
            "lilac",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "chartreuse",
            "amber",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "amber",
            "gold",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "cyan",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "amber",
            "lilac",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "rose",
            "cyan",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "violet",
            "rose",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "scarlet",
            "scarlet",
            "amber",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "blue",
            "blue",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-118",
    "number": 118,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 118,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 10
    },
    "metrics": {
      "colorCount": 10,
      "optimalMoves": 28,
      "segmentCount": 36,
      "exploredStates": 9862,
      "openingMoves": 20,
      "misleadingBranchRatio": 0.6,
      "difficultyRating": 0.74,
      "difficultyScore": 7400
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "rose",
            "amber",
            "gold",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "lilac",
            "gold",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "scarlet",
            "cyan",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "chartreuse",
            "amber",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "scarlet",
            "violet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "blue",
            "mint",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "gold",
            "amber",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "mint",
            "rose",
            "blue",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "mint",
            "scarlet",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-119",
    "number": 119,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 119,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 9
    },
    "metrics": {
      "colorCount": 9,
      "optimalMoves": 26,
      "segmentCount": 32,
      "exploredStates": 15162,
      "openingMoves": 18,
      "misleadingBranchRatio": 0.4444444444444444,
      "difficultyRating": 0.71,
      "difficultyScore": 7100
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "gold",
            "scarlet",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "blue",
            "cyan",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "rose",
            "lilac",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "blue",
            "scarlet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "violet",
            "cyan",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "amber",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "violet",
            "gold",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "mint",
            "mint",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "rose",
            "violet",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-120",
    "number": 120,
    "configVersion": "chapter-4.2026-09-05.1",
    "presentationSeed": 120,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 9
    },
    "metrics": {
      "colorCount": 9,
      "optimalMoves": 25,
      "segmentCount": 32,
      "exploredStates": 11466,
      "openingMoves": 18,
      "misleadingBranchRatio": 0.4444444444444444,
      "difficultyRating": 0.694,
      "difficultyScore": 6940
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "scarlet",
            "gold",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "mint",
            "scarlet",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "lilac",
            "cyan",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "lilac",
            "blue",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "violet",
            "rose",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "cyan",
            "rose",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "scarlet",
            "gold",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [
            "blue",
            "blue",
            "gold",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "lilac",
            "amber",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  }
];
