import type { LevelConfig } from './level-config.ts';

// Generated by tools/generate-chapter-six.ts. Do not edit by hand.
export const CHAPTER_SIX_LEVEL_DATA: readonly LevelConfig[] = [
  {
    "id": "level-151",
    "number": 151,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 151,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 36,
      "segmentCount": 42,
      "exploredStates": 16820,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.5454545454545454,
      "difficultyRating": 0.813,
      "difficultyScore": 8130
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "gold",
            "violet",
            "cyan",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "mint",
            "rose",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "violet",
            "chartreuse",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "rose",
            "scarlet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "blue",
            "mint",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "blue",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "lilac",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "chartreuse",
            "amber",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "scarlet",
            "indigo",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "amber",
            "amber",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "violet",
            "chartreuse",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-152",
    "number": 152,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 152,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 34,
      "segmentCount": 41,
      "exploredStates": 18872,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.45454545454545453,
      "difficultyRating": 0.79,
      "difficultyScore": 7900
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "gold",
            "chartreuse",
            "scarlet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "rose",
            "cyan",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "amber",
            "violet",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "indigo",
            "violet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "violet",
            "rose",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "mint",
            "indigo",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "blue",
            "scarlet",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "scarlet",
            "lilac",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "lilac",
            "mint",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "amber",
            "rose",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "blue",
            "rose",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-153",
    "number": 153,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 153,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 35,
      "segmentCount": 42,
      "exploredStates": 25316,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.45454545454545453,
      "difficultyRating": 0.806,
      "difficultyScore": 8060
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "blue",
            "violet",
            "mint",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "violet",
            "lilac",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "chartreuse",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "indigo",
            "mint",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "lilac",
            "amber",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "gold",
            "amber",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "cyan",
            "gold",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "scarlet",
            "rose",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "gold",
            "scarlet",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "rose",
            "amber",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-154",
    "number": 154,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 154,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 36,
      "segmentCount": 44,
      "exploredStates": 21116,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.5454545454545454,
      "difficultyRating": 0.816,
      "difficultyScore": 8160
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "rose",
            "indigo",
            "cyan",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "lilac",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "gold",
            "violet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "gold",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "indigo",
            "amber",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "blue",
            "amber",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "gold",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "violet",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "cyan",
            "mint",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "amber",
            "scarlet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "lilac",
            "cyan",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-155",
    "number": 155,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 155,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 36,
      "segmentCount": 44,
      "exploredStates": 30847,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.8181818181818182,
      "difficultyRating": 0.859,
      "difficultyScore": 8590
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "amber",
            "lilac",
            "chartreuse",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "gold",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "scarlet",
            "amber",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "indigo",
            "violet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "chartreuse",
            "cyan",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "amber",
            "blue",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "blue",
            "indigo",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "violet",
            "indigo",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "mint",
            "rose",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "rose",
            "lilac",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "indigo",
            "chartreuse",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-156",
    "number": 156,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 156,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 37,
      "segmentCount": 44,
      "exploredStates": 26331,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.5454545454545454,
      "difficultyRating": 0.819,
      "difficultyScore": 8190
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "lilac",
            "chartreuse",
            "indigo",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "cyan",
            "chartreuse",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "amber",
            "scarlet",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "rose",
            "indigo",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "cyan",
            "blue",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "gold",
            "cyan",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "gold",
            "blue",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "gold",
            "mint",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "amber",
            "scarlet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "mint",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "lilac",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-157",
    "number": 157,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 157,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 37,
      "segmentCount": 44,
      "exploredStates": 30820,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.5454545454545454,
      "difficultyRating": 0.821,
      "difficultyScore": 8210
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "violet",
            "lilac",
            "amber",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "gold",
            "blue",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "chartreuse",
            "blue",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "gold",
            "chartreuse",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "chartreuse",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "indigo",
            "cyan",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "gold",
            "mint",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "chartreuse",
            "mint",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "amber",
            "violet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "cyan",
            "mint",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "blue",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-158",
    "number": 158,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 158,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 37,
      "segmentCount": 43,
      "exploredStates": 27671,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.5454545454545454,
      "difficultyRating": 0.82,
      "difficultyScore": 8200
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "violet",
            "scarlet",
            "blue",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "violet",
            "cyan",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "chartreuse",
            "amber",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "gold",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "violet",
            "blue",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "lilac",
            "indigo",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "lilac",
            "chartreuse",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "cyan",
            "rose",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "amber",
            "lilac",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "blue",
            "chartreuse",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-159",
    "number": 159,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 159,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 36,
      "segmentCount": 43,
      "exploredStates": 51515,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.6363636363636364,
      "difficultyRating": 0.84,
      "difficultyScore": 8400
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "rose",
            "mint",
            "chartreuse",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "violet",
            "indigo",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "blue",
            "indigo",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "amber",
            "scarlet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "mint",
            "chartreuse",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "indigo",
            "scarlet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "gold",
            "indigo",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "violet",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "scarlet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "cyan",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "lilac",
            "lilac",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-160",
    "number": 160,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 160,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 36,
      "segmentCount": 43,
      "exploredStates": 33141,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.6363636363636364,
      "difficultyRating": 0.835,
      "difficultyScore": 8350
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "blue",
            "rose",
            "mint",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "amber",
            "mint",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "violet",
            "gold",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "indigo",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "indigo",
            "cyan",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "mint",
            "scarlet",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "scarlet",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "chartreuse",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "scarlet",
            "indigo",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "lilac",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "violet",
            "blue",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-161",
    "number": 161,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 161,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 36,
      "segmentCount": 43,
      "exploredStates": 31241,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.6363636363636364,
      "difficultyRating": 0.834,
      "difficultyScore": 8340
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "mint",
            "amber",
            "gold",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "amber",
            "cyan",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "gold",
            "amber",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "violet",
            "violet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "cyan",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "violet",
            "scarlet",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "blue",
            "violet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "rose",
            "scarlet",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "blue",
            "chartreuse",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "mint",
            "rose",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-162",
    "number": 162,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 162,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 37,
      "segmentCount": 44,
      "exploredStates": 31372,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.5454545454545454,
      "difficultyRating": 0.821,
      "difficultyScore": 8210
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "mint",
            "chartreuse",
            "indigo",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "blue",
            "scarlet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "gold",
            "blue",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "gold",
            "lilac",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "lilac",
            "cyan",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "blue",
            "cyan",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "amber",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "chartreuse",
            "blue",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "mint",
            "rose",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "lilac",
            "chartreuse",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-163",
    "number": 163,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 163,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 36,
      "segmentCount": 43,
      "exploredStates": 30823,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.45454545454545453,
      "difficultyRating": 0.808,
      "difficultyScore": 8080
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "cyan",
            "scarlet",
            "mint",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "amber",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "violet",
            "blue",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "amber",
            "scarlet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "blue",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "blue",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "cyan",
            "rose",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "indigo",
            "amber",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "gold",
            "amber",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "violet",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "cyan",
            "rose",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-164",
    "number": 164,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 164,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 36,
      "segmentCount": 42,
      "exploredStates": 34323,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.45454545454545453,
      "difficultyRating": 0.81,
      "difficultyScore": 8100
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "cyan",
            "mint",
            "amber",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "mint",
            "lilac",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "scarlet",
            "scarlet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "indigo",
            "cyan",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "lilac",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "mint",
            "rose",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "gold",
            "lilac",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "scarlet",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "indigo",
            "chartreuse",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "gold",
            "chartreuse",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "rose",
            "mint",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-165",
    "number": 165,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 165,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 36,
      "segmentCount": 43,
      "exploredStates": 50183,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.5454545454545454,
      "difficultyRating": 0.827,
      "difficultyScore": 8270
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "violet",
            "indigo",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "chartreuse",
            "rose",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "gold",
            "cyan",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "indigo",
            "amber",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "violet",
            "blue",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "lilac",
            "rose",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "scarlet",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "mint",
            "lilac",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "mint",
            "indigo",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "cyan",
            "scarlet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "cyan",
            "chartreuse",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-166",
    "number": 166,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 166,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 38,
      "segmentCount": 44,
      "exploredStates": 80708,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.45454545454545453,
      "difficultyRating": 0.821,
      "difficultyScore": 8210
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "amber",
            "blue",
            "rose",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "indigo",
            "mint",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "blue",
            "lilac",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "scarlet",
            "chartreuse",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "gold",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "lilac",
            "scarlet",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "amber",
            "mint",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "lilac",
            "mint",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "cyan",
            "gold",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "violet",
            "cyan",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "scarlet",
            "cyan",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-167",
    "number": 167,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 167,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 36,
      "segmentCount": 44,
      "exploredStates": 46878,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.45454545454545453,
      "difficultyRating": 0.814,
      "difficultyScore": 8140
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "violet",
            "gold",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "rose",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "violet",
            "rose",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "gold",
            "blue",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "indigo",
            "scarlet",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "scarlet",
            "rose",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "amber",
            "indigo",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "cyan",
            "amber",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "gold",
            "cyan",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "chartreuse",
            "cyan",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "mint",
            "lilac",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-168",
    "number": 168,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 168,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 45612,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.45454545454545453,
      "difficultyRating": 0.813,
      "difficultyScore": 8130
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "cyan",
            "chartreuse",
            "amber",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "indigo",
            "blue",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "chartreuse",
            "lilac",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "lilac",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "indigo",
            "lilac",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "indigo",
            "rose",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "gold",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "chartreuse",
            "cyan",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "amber",
            "blue",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "amber",
            "blue",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "lilac",
            "blue",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-169",
    "number": 169,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 169,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 36,
      "segmentCount": 42,
      "exploredStates": 73739,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.45454545454545453,
      "difficultyRating": 0.82,
      "difficultyScore": 8200
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "scarlet",
            "scarlet",
            "indigo",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "violet",
            "cyan",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "mint",
            "lilac",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "gold",
            "indigo",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "rose",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "cyan",
            "amber",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "amber",
            "blue",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "amber",
            "lilac",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "chartreuse",
            "violet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "chartreuse",
            "lilac",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "cyan",
            "rose",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-170",
    "number": 170,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 170,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 37,
      "segmentCount": 44,
      "exploredStates": 101313,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.5454545454545454,
      "difficultyRating": 0.837,
      "difficultyScore": 8370
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "amber",
            "rose",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "mint",
            "indigo",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "amber",
            "gold",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "indigo",
            "violet",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "scarlet",
            "rose",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "lilac",
            "scarlet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "blue",
            "lilac",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "violet",
            "mint",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "gold",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "indigo",
            "violet",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "blue",
            "indigo",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-171",
    "number": 171,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 171,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 38,
      "segmentCount": 43,
      "exploredStates": 53283,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.5454545454545454,
      "difficultyRating": 0.828,
      "difficultyScore": 8280
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "amber",
            "gold",
            "gold",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "chartreuse",
            "indigo",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "mint",
            "violet",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "mint",
            "violet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "rose",
            "cyan",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "cyan",
            "rose",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "cyan",
            "lilac",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "gold",
            "cyan",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "blue",
            "scarlet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "amber",
            "lilac",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "rose",
            "scarlet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-172",
    "number": 172,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 172,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 37,
      "segmentCount": 44,
      "exploredStates": 89140,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.45454545454545453,
      "difficultyRating": 0.822,
      "difficultyScore": 8220
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "lilac",
            "indigo",
            "chartreuse",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "amber",
            "chartreuse",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "blue",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "lilac",
            "indigo",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "mint",
            "amber",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "violet",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "chartreuse",
            "mint",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "mint",
            "cyan",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "rose",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "indigo",
            "gold",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "rose",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-173",
    "number": 173,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 173,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 37,
      "segmentCount": 44,
      "exploredStates": 56690,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.45454545454545453,
      "difficultyRating": 0.816,
      "difficultyScore": 8160
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "rose",
            "violet",
            "indigo",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "blue",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "cyan",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "lilac",
            "amber",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "scarlet",
            "gold",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "rose",
            "scarlet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "chartreuse",
            "mint",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "amber",
            "cyan",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "blue",
            "lilac",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "cyan",
            "violet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "cyan",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-174",
    "number": 174,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 174,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 38,
      "segmentCount": 44,
      "exploredStates": 68996,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.45454545454545453,
      "difficultyRating": 0.819,
      "difficultyScore": 8190
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "scarlet",
            "blue",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "violet",
            "rose",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "scarlet",
            "indigo",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "indigo",
            "violet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "lilac",
            "blue",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "rose",
            "amber",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "cyan",
            "blue",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "gold",
            "scarlet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "indigo",
            "amber",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "amber",
            "chartreuse",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "blue",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-175",
    "number": 175,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 175,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 38,
      "segmentCount": 44,
      "exploredStates": 68488,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.5454545454545454,
      "difficultyRating": 0.831,
      "difficultyScore": 8310
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "blue",
            "lilac",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "mint",
            "indigo",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "indigo",
            "mint",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "violet",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "chartreuse",
            "amber",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "blue",
            "violet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "mint",
            "chartreuse",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "amber",
            "gold",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "violet",
            "rose",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "indigo",
            "scarlet",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "scarlet",
            "rose",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-176",
    "number": 176,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 176,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 38,
      "segmentCount": 43,
      "exploredStates": 67247,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.45454545454545453,
      "difficultyRating": 0.818,
      "difficultyScore": 8180
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "rose",
            "chartreuse",
            "rose",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "indigo",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "violet",
            "cyan",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "mint",
            "scarlet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "lilac",
            "mint",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "violet",
            "scarlet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "violet",
            "gold",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "cyan",
            "lilac",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "amber",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "indigo",
            "mint",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-177",
    "number": 177,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 177,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 38,
      "segmentCount": 44,
      "exploredStates": 66890,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.8181818181818182,
      "difficultyRating": 0.869,
      "difficultyScore": 8690
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "indigo",
            "mint",
            "lilac",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "chartreuse",
            "scarlet",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "amber",
            "rose",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "cyan",
            "amber",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "violet",
            "lilac",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "gold",
            "scarlet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "violet",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "rose",
            "scarlet",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "cyan",
            "rose",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "indigo",
            "chartreuse",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "violet",
            "amber",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-178",
    "number": 178,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 178,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 38,
      "segmentCount": 44,
      "exploredStates": 34568,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.797,
      "difficultyScore": 7970
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "violet",
            "lilac",
            "rose",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "amber",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "lilac",
            "amber",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "gold",
            "mint",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "rose",
            "amber",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "blue",
            "indigo",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "mint",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "scarlet",
            "indigo",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "gold",
            "chartreuse",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "lilac",
            "blue",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "cyan",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-179",
    "number": 179,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 179,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 35,
      "segmentCount": 41,
      "exploredStates": 44450,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.8,
      "difficultyScore": 8000
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "mint",
            "violet",
            "chartreuse",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "lilac",
            "lilac",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "violet",
            "blue",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "gold",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "indigo",
            "rose",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "mint",
            "rose",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "mint",
            "blue",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "scarlet",
            "amber",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "chartreuse",
            "scarlet",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "rose",
            "indigo",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "rose",
            "indigo",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-180",
    "number": 180,
    "configVersion": "chapter-6.2026-09-19.1",
    "presentationSeed": 180,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 37,
      "segmentCount": 43,
      "exploredStates": 39469,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.799,
      "difficultyScore": 7990
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "rose",
            "chartreuse",
            "scarlet",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "blue",
            "lilac",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "violet",
            "cyan",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "mint",
            "chartreuse",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "mint",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "blue",
            "indigo",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "scarlet",
            "cyan",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "indigo",
            "gold",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "indigo",
            "cyan",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "lilac",
            "rose",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "amber",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  }
];
