import type { LevelConfig } from './level-config.ts';

// Generated by tools/generate-chapter-ten.ts. Do not edit by hand.
export const CHAPTER_TEN_LEVEL_DATA: readonly LevelConfig[] = [
  {
    "id": "level-271",
    "number": 271,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 271,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 38,
      "segmentCount": 44,
      "exploredStates": 78834,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.808,
      "difficultyScore": 8080
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "rose",
            "mint",
            "gold",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "mint",
            "gold",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "lilac",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "amber",
            "lilac",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "violet",
            "cyan",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "indigo",
            "cyan",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "lilac",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "gold",
            "mint",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "indigo",
            "rose",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "scarlet",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "violet",
            "lilac",
            "violet",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-272",
    "number": 272,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 272,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 68726,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.45454545454545453,
      "difficultyRating": 0.819,
      "difficultyScore": 8190
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "cyan",
            "rose",
            "scarlet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "mint",
            "scarlet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "mint",
            "violet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "indigo",
            "mint",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "violet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "rose",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "chartreuse",
            "amber",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "indigo",
            "amber",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "violet",
            "gold",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-273",
    "number": 273,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 273,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 97541,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.18181818181818182,
      "difficultyRating": 0.785,
      "difficultyScore": 7850
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "gold",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "chartreuse",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "violet",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "chartreuse",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "blue",
            "lilac",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "scarlet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "rose",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "chartreuse",
            "mint",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-274",
    "number": 274,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 274,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 122918,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.18181818181818182,
      "difficultyRating": 0.788,
      "difficultyScore": 7880
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "indigo",
            "violet",
            "lilac",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "gold",
            "chartreuse",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "violet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "rose",
            "amber",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "blue",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "amber",
            "mint",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "amber",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "scarlet",
            "gold",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "gold",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "lilac",
            "mint",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "chartreuse",
            "rose",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-275",
    "number": 275,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 275,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 69739,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.45454545454545453,
      "difficultyRating": 0.819,
      "difficultyScore": 8190
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "cyan",
            "rose",
            "scarlet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "mint",
            "scarlet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "mint",
            "violet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "lilac",
            "mint",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "violet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "rose",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "chartreuse",
            "amber",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "indigo",
            "amber",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "violet",
            "chartreuse",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-276",
    "number": 276,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 276,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 72035,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.807,
      "difficultyScore": 8070
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "cyan",
            "gold",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "chartreuse",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "violet",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "chartreuse",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "blue",
            "lilac",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "scarlet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "rose",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "chartreuse",
            "mint",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-277",
    "number": 277,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 277,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 111918,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.18181818181818182,
      "difficultyRating": 0.787,
      "difficultyScore": 7870
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "indigo",
            "violet",
            "lilac",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "lilac",
            "chartreuse",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "violet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "rose",
            "amber",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "blue",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "amber",
            "mint",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "amber",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "scarlet",
            "gold",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "gold",
            "violet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "gold",
            "mint",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "chartreuse",
            "rose",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-278",
    "number": 278,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 278,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 74865,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.6363636363636364,
      "difficultyRating": 0.845,
      "difficultyScore": 8450
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "cyan",
            "rose",
            "scarlet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "mint",
            "scarlet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "mint",
            "violet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "indigo",
            "mint",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "violet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "rose",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "chartreuse",
            "amber",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "indigo",
            "amber",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "violet",
            "gold",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-279",
    "number": 279,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 279,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 72141,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.2727272727272727,
      "difficultyRating": 0.794,
      "difficultyScore": 7940
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "gold",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "chartreuse",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "violet",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "chartreuse",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "blue",
            "lilac",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "scarlet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "rose",
            "violet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "chartreuse",
            "mint",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-280",
    "number": 280,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 280,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 135083,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.18181818181818182,
      "difficultyRating": 0.789,
      "difficultyScore": 7890
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "indigo",
            "violet",
            "lilac",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "lilac",
            "chartreuse",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "scarlet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "rose",
            "amber",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "blue",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "amber",
            "mint",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "amber",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "violet",
            "gold",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "gold",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "gold",
            "mint",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "chartreuse",
            "rose",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-281",
    "number": 281,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 281,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 40,
      "segmentCount": 44,
      "exploredStates": 68538,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.18181818181818182,
      "difficultyRating": 0.781,
      "difficultyScore": 7810
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "cyan",
            "rose",
            "scarlet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "mint",
            "scarlet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "mint",
            "violet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "indigo",
            "mint",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "violet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "rose",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "chartreuse",
            "amber",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "amber",
            "indigo",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "violet",
            "chartreuse",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-282",
    "number": 282,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 282,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 40,
      "segmentCount": 44,
      "exploredStates": 82701,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.18181818181818182,
      "difficultyRating": 0.783,
      "difficultyScore": 7830
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "gold",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "chartreuse",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "violet",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "mint",
            "chartreuse",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "blue",
            "lilac",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "scarlet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "rose",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "chartreuse",
            "mint",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-283",
    "number": 283,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 283,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 112019,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.18181818181818182,
      "difficultyRating": 0.787,
      "difficultyScore": 7870
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "indigo",
            "violet",
            "lilac",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "lilac",
            "chartreuse",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "rose",
            "violet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "rose",
            "amber",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "blue",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "amber",
            "mint",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "amber",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "scarlet",
            "gold",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "gold",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "gold",
            "mint",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "chartreuse",
            "rose",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-284",
    "number": 284,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 284,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 40,
      "segmentCount": 44,
      "exploredStates": 78679,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.2727272727272727,
      "difficultyRating": 0.795,
      "difficultyScore": 7950
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "rose",
            "gold",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "chartreuse",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "violet",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "chartreuse",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "blue",
            "lilac",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "scarlet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "chartreuse",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "chartreuse",
            "mint",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-285",
    "number": 285,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 285,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 80447,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.2727272727272727,
      "difficultyRating": 0.795,
      "difficultyScore": 7950
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "gold",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "chartreuse",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "scarlet",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "chartreuse",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "blue",
            "lilac",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "scarlet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "rose",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "chartreuse",
            "mint",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-286",
    "number": 286,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 286,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 106878,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.18181818181818182,
      "difficultyRating": 0.786,
      "difficultyScore": 7860
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "indigo",
            "violet",
            "lilac",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "lilac",
            "chartreuse",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "violet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "rose",
            "amber",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "blue",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "amber",
            "mint",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "amber",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "mint",
            "gold",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "gold",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "gold",
            "scarlet",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "chartreuse",
            "rose",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-287",
    "number": 287,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 287,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 40,
      "segmentCount": 44,
      "exploredStates": 71301,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.18181818181818182,
      "difficultyRating": 0.781,
      "difficultyScore": 7810
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "cyan",
            "rose",
            "scarlet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "mint",
            "scarlet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "mint",
            "violet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "indigo",
            "mint",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "violet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "lilac",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "chartreuse",
            "amber",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "indigo",
            "amber",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "chartreuse",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "violet",
            "chartreuse",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-288",
    "number": 288,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 288,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 87723,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.809,
      "difficultyScore": 8090
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "gold",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "chartreuse",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "violet",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "chartreuse",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "blue",
            "lilac",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "scarlet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "rose",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "chartreuse",
            "mint",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "blue",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-289",
    "number": 289,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 289,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 102292,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.2727272727272727,
      "difficultyRating": 0.798,
      "difficultyScore": 7980
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "indigo",
            "violet",
            "lilac",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "lilac",
            "chartreuse",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "violet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "rose",
            "amber",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "blue",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "amber",
            "mint",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "scarlet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "scarlet",
            "gold",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "gold",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "gold",
            "mint",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "chartreuse",
            "rose",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-290",
    "number": 290,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 290,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 40,
      "segmentCount": 44,
      "exploredStates": 72727,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.45454545454545453,
      "difficultyRating": 0.819,
      "difficultyScore": 8190
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "cyan",
            "rose",
            "scarlet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "mint",
            "scarlet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "mint",
            "violet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "indigo",
            "mint",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "violet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "rose",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "chartreuse",
            "amber",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "indigo",
            "amber",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "scarlet",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "violet",
            "chartreuse",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-291",
    "number": 291,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 291,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 74883,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.807,
      "difficultyScore": 8070
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "cyan",
            "gold",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "chartreuse",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "violet",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "chartreuse",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "blue",
            "lilac",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "chartreuse",
            "mint",
            "scarlet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "rose",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "chartreuse",
            "mint",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-292",
    "number": 292,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 292,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 116389,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.18181818181818182,
      "difficultyRating": 0.787,
      "difficultyScore": 7870
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "indigo",
            "violet",
            "lilac",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "lilac",
            "chartreuse",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "scarlet",
            "violet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "rose",
            "amber",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "rose",
            "blue",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "amber",
            "mint",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "amber",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "scarlet",
            "gold",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "gold",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "gold",
            "mint",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "chartreuse",
            "rose",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-293",
    "number": 293,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 293,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 40,
      "segmentCount": 44,
      "exploredStates": 136193,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.18181818181818182,
      "difficultyRating": 0.789,
      "difficultyScore": 7890
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "cyan",
            "rose",
            "scarlet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "mint",
            "scarlet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "mint",
            "violet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "indigo",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "violet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "rose",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "chartreuse",
            "amber",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "indigo",
            "amber",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "violet",
            "chartreuse",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-294",
    "number": 294,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 294,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 92641,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.81,
      "difficultyScore": 8100
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "gold",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "chartreuse",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "violet",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "chartreuse",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "blue",
            "lilac",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "scarlet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "rose",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "chartreuse",
            "mint",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-295",
    "number": 295,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 295,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 40,
      "segmentCount": 44,
      "exploredStates": 75565,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.09090909090909091,
      "difficultyRating": 0.769,
      "difficultyScore": 7690
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "cyan",
            "rose",
            "scarlet",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "mint",
            "scarlet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "gold",
            "mint",
            "violet",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "indigo",
            "mint",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "gold",
            "violet",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "rose",
            "mint",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "chartreuse",
            "amber",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "indigo",
            "amber",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "chartreuse",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "violet",
            "chartreuse",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-296",
    "number": 296,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 296,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 89549,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.809,
      "difficultyScore": 8090
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "gold",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "chartreuse",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "violet",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "chartreuse",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "blue",
            "lilac",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "scarlet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "rose",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "chartreuse",
            "mint",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "violet",
            "blue",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-297",
    "number": 297,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 297,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 111133,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.18181818181818182,
      "difficultyRating": 0.787,
      "difficultyScore": 7870
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "indigo",
            "violet",
            "lilac",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "lilac",
            "chartreuse",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "scarlet",
            "violet",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "rose",
            "amber",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "blue",
            "scarlet",
            "blue",
            "lilac"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "amber",
            "mint",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "cyan",
            "amber",
            "rose"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "rose",
            "gold",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "scarlet",
            "gold",
            "violet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "gold",
            "mint",
            "cyan"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "chartreuse",
            "rose",
            "chartreuse"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-298",
    "number": 298,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 298,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 69027,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.806,
      "difficultyScore": 8060
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "blue",
            "gold",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "chartreuse",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "violet",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "chartreuse",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "blue",
            "lilac",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "scarlet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "rose",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "chartreuse",
            "mint",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "chartreuse",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-299",
    "number": 299,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 299,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 66538,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.806,
      "difficultyScore": 8060
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "gold",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "mint",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "violet",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "chartreuse",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "blue",
            "lilac",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "chartreuse",
            "scarlet",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "rose",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "chartreuse",
            "mint",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  },
  {
    "id": "level-300",
    "number": 300,
    "configVersion": "chapter-10.2026-09-24.1",
    "presentationSeed": 300,
    "capacity": 4,
    "slotCount": 15,
    "rewardSlotIndex": 14,
    "completionRule": {
      "type": "all-colors",
      "targetCount": 11
    },
    "metrics": {
      "colorCount": 11,
      "optimalMoves": 39,
      "segmentCount": 44,
      "exploredStates": 83532,
      "openingMoves": 22,
      "misleadingBranchRatio": 0.36363636363636365,
      "difficultyRating": 0.809,
      "difficultyScore": 8090
    },
    "initialState": {
      "bottles": [
        {
          "layers": [
            "chartreuse",
            "gold",
            "scarlet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "rose",
            "chartreuse",
            "rose",
            "mint"
          ],
          "status": "active"
        },
        {
          "layers": [
            "indigo",
            "violet",
            "gold",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "mint",
            "rose",
            "chartreuse",
            "gold"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "scarlet",
            "gold",
            "violet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "amber",
            "blue",
            "lilac",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "blue",
            "lilac",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "mint",
            "chartreuse",
            "blue"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "rose",
            "violet",
            "scarlet"
          ],
          "status": "active"
        },
        {
          "layers": [
            "lilac",
            "scarlet",
            "mint",
            "indigo"
          ],
          "status": "active"
        },
        {
          "layers": [
            "cyan",
            "blue",
            "violet",
            "amber"
          ],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "active"
        },
        {
          "layers": [],
          "status": "inactive"
        },
        {
          "layers": [],
          "status": "reserved"
        }
      ],
      "rewardBottleUsed": false,
      "moves": 0
    }
  }
];
